# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVnmSn1qC8fbvjr6jYUhl61irE-bBEoN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

dataset = pd.read_csv('train.csv')
dataset=dataset.dropna(how='any')
dataset

x=dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
print(y)

y=y.reshape(len(y),1)

print(y)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=1)

ytest

from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(xtrain,ytrain)

plt.scatter(xtrain,ytrain,color='red')
plt.plot(xtrain,lr.predict(xtrain),color='green')
plt.title('Train values' )
plt.xlabel('xtrain')
plt.ylabel('ytrain')
plt.show()

plt.scatter(xtest,ytest,color='red')
plt.plot(xtrain,lr.predict(xtrain),color='green')
plt.title('Test values' )
plt.xlabel('xtest')
plt.ylabel('ytest')
plt.show()

ypred=lr.predict(xtest)
np.set_printoptions(precision=2)
print(np.concatenate((ypred.reshape(len(ypred),1), ytest.reshape(len(ytest),1)),1))

print(lr.coef_)
print(lr.intercept_)

print(lr.predict([[20]]))

from sklearn.metrics import r2_score
a=r2_score(ytest, ypred)
print(abs(a*100))

